version: '3.8'

services:
  cbsdb:
    image: mysql:8.0
    container_name: cbsdbc1
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
  
  cbsflaskwebapp:
    image: cbsflask:webappv1
    build: .
    ports:
      - "4890:5000" #hostport:container
    environment:
      FLASK_ENV: development
      MYSQL_HOST: cbsdb
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: testdb
    depends_on:
      - cbsdb

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Example12345
      MYSQL_DATABASE: testdb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: